### ISSUE TITLE
Issue with parallelization in regression.py

### ISSUE THREAD

**Issue by JPT2** [erp12/pyshgp#100]
Hi, when I try running the regression.py with n_jobs = -1 I get the following error

> RuntimeError:
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.

**Comment by erp12** [comment]
Thanks for reporting this! I haven't seen this issue before but I can definitely dig into it. I just attempted to recreate the error on a clean version of master and was unable to. Would you mind providing a little bit more information about the error?

Can you post more of the stack trace? I suspect the error is being thrown by the Pathos library, but I wan't to be sure.
Does the error happen immediately after evolution starts or do a few generations happen successfully before you see the error?

**Comment by JPT2** [comment]
I ran the program with n_jobs = 2 to produce the following:
[pyshStackTrace.txt](https://github.com/erp12/pyshgp/files/2462172/pyshStackTrace.txt)

The error happens before any generations happen, and it appears the program tries again and again to restart as it prints out 
[output.txt](https://github.com/erp12/pyshgp/files/2462178/output.txt) before printing out the error and same output again and it will continue to repeat this behavior until interrupted.

**Comment by erp12** [comment]
I was never able to reproduce this, but parallelism was pulled out for the reboot and just re-added in #123. It's implemented a little differently so I am going to close this for now but if you still have issues, feel free to re-open the issue.
