### ISSUE TITLE
Put sane limits on numbers and strings.

### ISSUE THREAD

**Issue by erp12** [erp12/pyshgp#126]
In my preparation for the next big release I am focusing a lot on full-run tests and benchmarks in order to enable future development which focuses on improving certain key metrics such as search performance and runtime. As expected, this requires a lot of runs. I have noticed that ever so often (but more frequently than I would like) I get runs which never seem to progress.

It is clear that Pyshgp does not defend against long running programs well enough. We already stop program interpretation after `n` steps of the interpreter, however we do not constrain values encountered by program execution. This could result in some nasty operations occurring in some instructions multiple times per program execution, effectively halting evolution.

**Comment by lspector** [comment]
In Clojush we have limits on everything, for example `max-string-length` and numeric limits enforced with `keep-number-reasonable`. There has been discussion about more principled ways to do this, and I think some of Tozier's systems have taken more sophisticated approaches. But FWIW I think imposing limits for everything is a practical and probably good-enough approach. What to do when the limits are exceeded? I think Clojush is inconsistent, with numbers being clamped to the limit and at least in some other cases (like in `string_concat`) the instruction acting as a no-op if it would exceed the limit. Consistency would probably be good here, I guess.

**Comment by erp12** [comment]
#127 added limits on string (and vector, code block, etc) lengths. I am not convinced that limits on numbers will help much here. I am going to close this issue for now. If I still see weird hangs, I will revisit this.
