### ISSUE TITLE
Lexicase shuffle

### ISSUE THREAD

**Issue by RedBeansAndRice** [erp12/pyshgp#130]
Is lexicase shuffling remaining test cases within the loop of a given call of select_one?

**Comment by erp12** [comment]
Lexicase selection should shuffle cases once per section. The current implementation performs the shuffle on line 205 of `selection.py`. (See below).

https://github.com/erp12/pyshgp/blob/f1d8170f49780dcc459afd77d43a47246b395ab0/pyshgp/gp/selection.py#L203-L212

I just reviewed the rest of the implementation for lexicase and it seems correct to me. Are you seeing additional shuffling within the loop?

**Comment by erp12** [comment]
Closing this issue because I believe the implementation of lexicase is correct. If you think I am missing something, feel free to re-open.
