### ISSUE TITLE
Use a dev branch

### ISSUE THREAD

**Issue by rhiever** [erp12/pyshgp#62]
Great to see all this progress on the pyshgp package. I strongly recommend using a separate development branch for developing the module, and dedicate the master branch to the latest release on pip. I got thrown off for a bit because I was installing pyshgp via pip but referring to examples on the latest dev version on GitHub.

**Comment by erp12** [comment]
Great suggestion. I will do this from now on.

These kinds of repository best-practices are things that pyshgp is in desperate need of. This is the first project I have maintained that has the potential to be used by others, so I need all the help I can get! If you come across more things like this, please feel free to open more issues!

Also, be aware that I struggled to get pyshgp on pip. I was under the impression that all my attempts had failed and it was not possible to get pyshgp from pip yet. If there is something there, it is out of date (as you noticed). This is on the to-do list right after I finish up a fair amount of refactoring on the gp modules.

**Comment by rhiever** [comment]
pyshGP is indeed on pip: https://pypi.python.org/pypi/pyshgp

You can log in there to remove it if you prefer.

You can look at the [TPOT repo](https://github.com/rhiever/tpot) for other examples of good practices for OSS on GitHub. Some random tips:

* Add a license and a `LICENSE` file in your repo ASAP! I recommend the MIT license unless other dependencies in the software require a more restrictive license.

* Write unit tests and use a service like TravisCI for continuous integration

* Use a service like landscape.io to continuously check your code quality and how it confirms to PEP8

* Write a contributor's guide to help potential contributors know how to properly contribute to the project

**Comment by erp12** [comment]
- License added in `LICENSE.md`
- There are way more unit tests now. Coverage is tracked using Codacy.
- Code style and other things also tracked by Codacy. It is now setup to comment on every PR.
- Contributor guide has been added to the ReadTheDocs [here](http://pysh2.readthedocs.io/en/latest/contributing.html).

Thank you for these awesome suggestions! I think the repo is in a much better state now and from here on out I will be sticking much more strictly to these best practices.

I removed `pyshgp` from pip and will add it back once the Beta 0.1 milestone is reached.

I looked around some other repos, including TPOT, sklearn, DEAP and others. It looks to me like projects either:

1) Use a `dev` branch where `master` is what is on pypi and `dev` branch is where new PRs go into. I suppose it would be up to the maintainers when to merge `dev` into `master` and create a new release.
2) Or use `master` as the bleeding edge branch, and a locked branch is created every time a new release is cut. The branch has the version's name (ie. v0.1) or something similar.

I am curious to hear your thoughts on these two options, or if you have any other options.

**Comment by erp12** [comment]
The feature-branch patter has been working well for now. 
Once pyshgp makes its way (back) to pip I would like to take the following pattern:

1. A "pre" version branch will be created (ie. "v0.3-pre")
2. Feature branches (including on forks) will be used to add individual features. Once complete, these branches will be merged into the pre-version branch via a PR.
3. Once the pre-version branch contains all features desired in the next release, the pre-version branch will be merged into master and a locked version branch will be created. (ie. "v0.3").

I have documented this workflow in the contributing guide and I am going to close this issue.
